version: '3.5'
services:
  mosquitto:
    container_name: ${CONTAINER_MQTT_WEB}
    image: eclipse-mosquitto:latest
    restart: always
    ports:
       - "1883:1883"
       - "8883:8883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/data/pwfile:/etc/mosquitto/pwfile
      - ./mosquitto:/var/lib/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - TZ="Europe/Paris"
      - PGID=1002
      - PUID=1002
      - MQTTHOSTNAME= ${DOMAINS}
      - DOMAIN= ${DOMAINS}
      - VIRTUAL_HOST= ${DOMAINS}
      - LETSENCRYPT_HOST= ${DOMAINS}
      - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}

networks:
    default:
       external:
         name: ${NETWORK}
